CREATE TABLE user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    bank_id VARBINARY(191) NOT NULL,
    credit BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE jpyen (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id VARBINARY(191) NOT NULL,
    amount BIGINT NOT NULL,
    note VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    INDEX user_id_idx (user_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;
