requires 'DBIx::Sunny';
requires 'DBD::mysql';
requires 'JSON::XS', '3.00';
requires 'JSON::Types';
requires 'Kossy';
requires 'Plack::Builder';
requires 'Plack::Session';
requires 'Time::Moment';
requires 'Furl';
requires 'Exception::Tiny';
requires 'Class::Accessor::Lite';
requires 'Crypt::Eksblowfish::Bcrypt';
requires 'Try::Tiny';
requires 'Guard';

on configure => sub {
    requires 'ExtUtils::MakeMaker';
};

on test => sub {
    requires 'Test::More';
};
