requires 'DBIx::Sunny';
requires 'DBD::mysql';
requires 'JSON::XS', '3.00';
requires 'JSON::Types';
requires 'Kossy';
requires 'Plack::Builder';
requires 'Plack::Session';
requires 'Time::Moment';
requires 'Furl';
requires 'Exception::Tiny';
requires 'Class::Accessor::Lite';
requires 'Try::Tiny';
requires 'Guard';
requires 'Starlet';
requires 'Digest::Bcrypt';
requires 'Data::Entropy::Algorithms';
requires 'IO::Socket::SSL';
requires 'Log::Minimal';
requires 'Devel::KYTProf';

on configure => sub {
    requires 'ExtUtils::MakeMaker';
};

on test => sub {
    requires 'Test::More';
};
